### ISSUE TITLE
Hue Firmware Update

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-ota-plugin#10]
Today Philips published firmware updates for various lights. Any chance to update the lights with deCONZ?

**Comment by Webunity** [comment]
Hi @mkaay are you willing to disclose more info / will you keep the list updated somehow?

**Comment by ottelo9** [comment]
> > Any idea why the update does not run? I select the node I want to update. Select the file and click update. Progress changes from "No file" to "Idle".
> 
> > Are you running the latest OTAU plugin (in .76 or .77). Make sure manufacturer and image type from the device (in table) match those of the file (in fields above the tabel). Hue devices will only update to a newer version.
> 
> I am also having this problem when trying to update a Hue motion sensor. The IDs match, and the version is newer.

me, too

**Comment by ebaauw** [comment]
As with any sleepy device, make sure to wake it by pressing a button when pressing _Update_.  This might take multiple attempts.

**Comment by BobSilent** [comment]
I have also a hue for the wiki, but i do not know where to get the image type information (in deconz cluster info i just see 0xffff) 

LCT026 - Hue Go (2nd Gen)
my FW Version: 1.56.7_r29434

I read here: https://www2.meethue.com/en-us/support/release-notes/lamps there should be a FW Version 1.56.8_r30456
an maybe also 1.65.11_hB798F2BF because this is for Bluetooth devices.

**Comment by ebaauw** [comment]
Make sure you’re on a recent version of deCONZ, open the panel for the OTAU plugin, select the Go in the map, and press _Query_.  That should read the _Image Type_ (and other attributes) into the table row.

**Comment by BobSilent** [comment]
I updated my previous comment, Column Image says 0x0111
and Version:  0x01001000

**Comment by ebaauw** [comment]
@BobSilent, The corresponding firmware file (see README) has version 0x01001600, which is later.  Could you please report after upgrading what the new _SW Build ID_ value is?  Note that you need to read the _Basic_ cluster attributes manually after the update, to refresh them.

**Comment by BobSilent** [comment]
ok, update went well, unfortunately i did not had the time to watch the progress, but everything seems to work
and now it reports `SW Build ID = 1.65.9_hB3217DF4`

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> I managed to reverse engineer the bridge communication with the firmware service and brute forced some image ids to get the firmware responses.
> You can find the responses here: https://gist.github.com/mkaay/6f19594fa77792f107e8b5e3c438d9f2
> That should be all of the available firmware files in the newest versions.

@ambvdijk @JeroenKnoops @marcofranssen @sjaakiejj can you please help us to get a ota-json list like ikea provide it 🙏

**Comment by mkaay** [comment]
FYI the gist has not the newest versions anymore.
You can use this json file: https://github.com/Koenkk/zigbee-OTA/blob/master/index.json
If i find new versions I'll add them there and here in the README.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> FYI the gist has not the newest versions anymore.
> You can use this json file: https://github.com/Koenkk/zigbee-OTA/blob/master/index.json
> If i find new versions I'll add them there and here in the README.

THX. Just want to involve @philips-labs & @philips-software to that problem. I am sure that they want be as cool as ikea :D and I am sure they want to share this information with us to get more security out there for all HUE users.

**Comment by drigga1512** [comment]
> Make sure you’re on a recent version of deCONZ, open the panel for the OTAU plugin, select the Go in the map, and press _Query_. That should read the _Image Type_ (and other attributes) into the table row.

I can‘t find the „Go“ in the map. 
For me the attributes only start to load if I select a firmware file. But I‘m not sure whether these attributes are attributes of the bulb firmware or the attributes of the firmware file.

**Comment by ebaauw** [comment]
Do you have a Hue Go?

**Comment by drigga1512** [comment]
> Do you have a Hue Go?

Ah Sry, thought that you meant a button in the app:) Now I got it. Tks for help

**Comment by JeroenKnoops** [comment]
> THX. Just want to involve @philips-labs & @philips-software to that problem. I am sure that they want be as cool as ikea :D and I am sure they want to share this information with us to get more security out there for all HUE users.
> Let us qoute them:
> https://github.com/philips-software/philips-howto-open-source#2-motivation
Unfortunately we cannot help you. All Hue related stuff has been moved out of Philips to Signify. Maybe the people behind PhilipsHue github organization can help you: https://github.com/PhilipsHue

**Comment by gvdhoven** [comment]
@mkaay  how do i know which version of the firmware i need to download? I have Philips Hue White Ambiance GU10 with BLE (350 lumen); is that the 0112 version or the 0114 version?

**Comment by sorryusernameisalreadytaken** [comment]
Can somebody explain what went wrong on my system?

My system:
rpi4 with raspbian-os
using deconz with docker from marthoc with deconz 2.05.84 , here is my compose yml:
```
version: '3'

services:
  deconz:
    container_name: deconz
    image: marthoc/deconz
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ipi/settings/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /home/ipi/settings/deconz/firmware-files:/root/otau
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=8181
      - DECONZ_WS_PORT=8182
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=Changemenot1132424
      - DECONZ_VNC_PORT=9999
      - UDEV=1
    privileged: true
    restart: unless-stopped
```
Download all known hue-firmware files from here into /home/pi/settings/deconz/firmware-files:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions

Then I start the vnc connection and enable otau-plugin:
![01](https://user-images.githubusercontent.com/12913436/95704327-c1024300-0c50-11eb-89f1-c13f41be98dc.PNG)
For example update I try this LCT012:
![02](https://user-images.githubusercontent.com/12913436/95704355-d5464000-0c50-11eb-98da-496d5692f493.PNG)
![03](https://user-images.githubusercontent.com/12913436/95704368-db3c2100-0c50-11eb-9beb-d3e8044eecc0.PNG)
Select this LCT012 devcie and click on file:
![04](https://user-images.githubusercontent.com/12913436/95704432-18081800-0c51-11eb-8274-33ad63e2680c.PNG)
![06](https://user-images.githubusercontent.com/12913436/95704544-7b924580-0c51-11eb-803f-9b355c11be0b.PNG)
Then I click on update:
![05](https://user-images.githubusercontent.com/12913436/95704518-60273a80-0c51-11eb-9cf7-739dc8c46eeb.PNG)
Sadly nothing happened here:
![07](https://user-images.githubusercontent.com/12913436/95704577-96fd5080-0c51-11eb-8e6c-e53f0b59a535.PNG)

What is wrong on my setup?

**Comment by Hypfer** [comment]
@sorryusernameisalreadytaken you might need to re-read the firmware version property of the basic cluster for it to change in phoscon.

Also, you can use [these](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to create a spoiler tag which is very useful for large comments like yours

**Comment by mkaay** [comment]
@gvdhoven The lamp should tell you what version it needs. I'm not using Deconz myself, but from the screenshots that have been posted here, there should be an "Image" column that contains the image version you need to download.
Unfortunately there is no mapping of product name/code to image version available via the API.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> @sorryusernameisalreadytaken you might need to re-read the firmware version property of the basic cluster for it to change in phoscon.

Where and how can I do this?

@Hypfer sorry it seems I can ot put images intos the spoiler-details tags :/

**Comment by gvdhoven** [comment]
Actually @mkaay the link posted by @sorryusernameisalreadytaken shows me that my White Ambiance (BLE) GU10 bulbs have code 0x0114. Problem solved 👍

**Comment by sorryusernameisalreadytaken** [comment]
Okay, I think my marthoc-deconz docker allready update all my HUE lights and switches. Ihink this is my only problem:
> 
> 
> > After deleting it and pairing it again, it showed up as new light with the correct firmware version. So it seems, that there is an Issue with updating FW versions after OTA update.
> 
> You need to force-read the _Basic_ cluster attributes before the GUI and REST API show the new firmware (and date code?). If the new firmware exposes a different profile or device id (e.g. upgrade from ZLL to Zigbee 3.0, which uses ZHA), you need to delete and re-pair the device. Just force-reading the _Simple Descriptors_ isn't enough to update the GUI.

I did this now with one LCT015 and the result is that I can see the new fw:
![grafik](https://user-images.githubusercontent.com/12913436/95837565-04d47580-0d41-11eb-989c-ca8508f801fe.png)

But it seems that OTAU still showed me the old fw (?)
![grafik](https://user-images.githubusercontent.com/12913436/95836923-4dd7fa00-0d40-11eb-99a3-14756cc55ea3.png)

How long does it take to see the model, vendor and firmware again in the node-list?
![grafik](https://user-images.githubusercontent.com/12913436/95837121-85df3d00-0d40-11eb-80dd-f5cf2f2a5078.png)

What is the easyest way to solve this for 
26 devices :D ?

**Comment by Hypfer** [comment]
Since it's just a meaningless string and you know that they're running the latest firmware, I'd strongly suggest completely ignoring it.

The easiest way to update multiple lights is to download all firmwares to `~/otau/` and then deconz should automatically update every light in the background by selecting the appropriate image. No manual work needed. Just download all of them

If it doesn't you might need to enable the Otau server in the old web interface's advanced settings

**Comment by sorryusernameisalreadytaken** [comment]
> The easiest way to update multiple lights is to download all firmwares to `~/otau/` and then deconz should automatically update every light in the background by selecting the appropriate image. No manual work needed. Just download all of them
> 
> If it doesn't you might need to enable the Otau server in the old web interface's advanced settings
THX for that information. It seems for me that my deconz this endless :D

> 
> 
> > THX. Just want to involve @philips-labs & @philips-software to that problem. I am sure that they want be as cool as ikea :D and I am sure they want to share this information with us to get more security out there for all HUE users.
> > Let us qoute them:
> > https://github.com/philips-software/philips-howto-open-source#2-motivation
> 
> Unfortunately we cannot help you. All Hue related stuff has been moved out of Philips to Signify. Maybe the people behind PhilipsHue github organization can help you: https://github.com/PhilipsHue

THX for the idea. Lets do it 👍 
@MartinDrost @Kakifrucht @gobo-ws @DillonN @anas10 @SpyderScript @stefanschoeberl @yadomi @PattyBakenSignify @Atilla-Bilgic @PhilipsHue
**Can anybody of you helps us to focus our time on fixing update-process instead of sniffing ota urls for hue devices?**

**Comment by Hypfer** [comment]
Can you not mass-highlight users

**Comment by ottelo9** [comment]
I've problem updating one of my Hue Dimming Switch firmware (RWL020). I successfully had updated 10 of my 11 switches to 28573 (0x42006f9d) from 0x42003f89. But one of my switches wont update. Its firmware version is 17846 (0x420045b6). In the deconz GUI (vnc) it will only show "idle". I've tried several times (press a button and then press update, reread the basic cluster ...). Anyone had/have the same problem? Any hints for me?

**Comment by Magoo2** [comment]
Updating Hue products seems not to be so easy :-(
I've updated a Hue Being White Ambiance without problems, thanks for the good work here.

But I have big problems with the Hue motion sensors. When i start the Update after a few seconds, i will stuck in the "Queued" Progress. Maybe you have some solutions for me?

**Comment by ottelo9** [comment]
@Magoo2 
Wait until next day. In my case after a day or so my Motion Sensors and Dimm Switches are updated.

**Comment by Magoo2** [comment]
Waiting for the other day doesn't help :( 
Hopefully someone has another idea what i can do?

**Comment by ottelo9** [comment]
Whats the battery level of your sensors?

> Waiting for the other day doesn't help :(
> Hopefully someone has another idea what i can do?

**Comment by bcutter** [comment]
What´s the best way to update firmware of Philips Hue devices when using Phoscon/deCONZ (ConBee 2)?
Where to get latest firmware OTA files?

**Comment by ottelo9** [comment]
@bcutter 
https://github.com/dresden-elektronik/deconz-ota-plugin

**Comment by jdeluyck** [comment]
I'm trying to get a motion sensor (Hue) to update. Downloaded the update, put it in /data/otau, deconz finds it and does it's magic.

Then added it with the STD Otau plugin, and it stays in 'Queued'...

**Comment by woytekbode** [comment]
@jdeluyck any luck? I have the same problem with the hue motion sensor. Followed the same steps, everything appears alright but it hangs on "queued".

**Comment by jdeluyck** [comment]
> @jdeluyck any luck? I have the same problem with the hue motion sensor. Followed the same steps, everything appears alright but it hangs on "queued".

None sofar. Once it stared but hung at 7%.

**Comment by woytekbode** [comment]
@jdeluyck I have made progress, check my newly opened issue!

**Comment by jdeluyck** [comment]
#27

**Comment by Tamas-Toth-ebola** [comment]
Hi @Hypfer !

I'm very glad to found this thread as with your help I could successfully upgrade my old _(2019)_ 'Hue - Fair' ceiling lamp firmware from the original `1.16.1_r19181 (20160907)` to `1.88.1 (20210331)` in 2 step _( > `01001904` > `01001F00` )_ with Home Assistant/'zigpy' through 'SONOFF - Zigbee 3.0 USB Dongle Plus' what is I know that somewhat off-topic, but the chronology here the thread helped me a lot.

I just report it here **if you want to put the device ID into the 'OTA Image Types Firmware versions' manual/documentation?!** The device ID is `LTC002`, and the firmware type is `0x010e`, and the lamp is an old 'Hue - Fair' _(behind 40340/30/P7 model code)_.

Thanks to all of you for your help in this thread!

**Comment by popy2k14** [comment]
@Tamas-Toth-ebola 
Thanks for your post.
deconz was updating my ~60x LWB010 (vendor 0x100B & Image 0x010C) in an loop from 1.46.13_r26312 (01001A00) to 1.88.1 (01002100).

After reading your post, i tried a middle step to 1.50.2_r30933 (01001A02), and that worked!

thx

**Comment by Hypfer** [comment]
@Tamas-Toth-ebola @popy2k14 

Thank you!
I completely forgot about this.

Recently, I've bought a few used Hue Signes (0x010E), which occasionally just rebooted. I didn't bother looking into it though.
After reading your comments, I did check the current firmware version and discovered that those were stuck in an endless update-reboot-loop as well.

**Comment by popy2k14** [comment]
@Hypfer thx for creating an issue for this.

@Tamas-Toth-ebola 
I am with you, that should be noted in EVERY wiki document!
Like here: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions
...and so on...

**Comment by OosieW** [comment]
> Hi @Hypfer !
> 
> I'm very glad to found this thread as with your help I could successfully upgrade my old _(2019)_ 'Hue - Fair' ceiling lamp firmware from the original `1.16.1_r19181 (20160907)` to `1.88.1 (20210331)` in 2 step _( > `01001904` > `01001F00` )_ with Home Assistant/'zigpy' through 'SONOFF - Zigbee 3.0 USB Dongle Plus' which is I know that somewhat off-topic, but the chronology here the thread helped me a lot.
(...)

@Tamas-Toth-ebola Where did you get the firmware file with version 1.88.1, used for this upgrade? At https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions I only see version 1.50.2_r30933.

**Comment by Tamas-Toth-ebola** [comment]
> > Hi @Hypfer !
> > I'm very glad to found this thread as with your help I could successfully upgrade my old _(2019)_ 'Hue - Fair' ceiling lamp firmware from the original `1.16.1_r19181 (20160907)` to `1.88.1 (20210331)` in 2 step _( > `01001904` > `01001F00` )_ with Home Assistant/'zigpy' through 'SONOFF - Zigbee 3.0 USB Dongle Plus' which is I know that somewhat off-topic, but the chronology here the thread helped me a lot.
> > (...)
> 
> @Tamas-Toth-ebola Where did you get the firmware file with version 1.88.1, used for this upgrade? At https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions I only see version 1.50.2_r30933. Also having a Fair ceiling lamp (LTC002) and firmware version now is 20191218.

Hi @OosieW !

You can download the latest publicly 'reachable' firmwares from KoenkK's repo: https://github.com/Koenkk/zigbee-OTA/blob/master/index.json - search for ` "imageType": 270,` for LTC002. The current latest is 1.101.2, just some months old, which is the `/100B-010E-01002300-ConfLight-ModuLum_0012.zigbee`, the previous version was the 1.88.1 with filename `[100B-010E-01001F00-ConfLight-ModuLum_0012.zigbee` but **for both of them you have to use minimally the 1.50.2** with filename `100B-010E-01001904-ConfLight-ModuLum_0012.zigbee` as from previous firmware versions you can not upgrade to the current ones in one step. The 1.88.1 is no longer available from KoenkK as there is a fresher one which of course includes all the previous extras/fixes.

I hope I could help you, and wish you a Happy New Year!
