### ISSUE TITLE
Update 100 nodes with the correct firmware

### ISSUE THREAD

**Issue by ChrisPrefect** [dresden-elektronik/deconz-ota-plugin#11]
I downloaded the tradfri firmware and opened the STD OATU plugin. But it is impossible to find the correct address to a specific device type and select the right firmware and then flash the device and repeat that for all 98 devices.

How can this be done? This absolutely has do work somehow automatically.

![image](https://user-images.githubusercontent.com/3579863/84330890-e3902c80-ab88-11ea-95a1-564ca72f862e.png)

For reference: Script to download the firmware files: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/ikea-ota-download.py

**Comment by ChrisPrefect** [comment]
Thank you! Is there a way to get the latest version without having to compile it? 

![image](https://user-images.githubusercontent.com/3579863/84608287-f620a380-aeb1-11ea-8555-c02b381cc6c1.png)

Would it help with reliability and speed to use a Raspberry Pi 4? I have one laying around and could just swap the SD card and ConBee-Stick over?

**Comment by ebaauw** [comment]
> Thank you! Is there a way to get the latest version without having to compile it?

Yes upgrade to the latest deCONZ version, as I've said above.

> Would it help with reliability and speed to use a Raspberry Pi 4? I have one laying around and could just swap the SD card and ConBee-Stick over?

Never tried that.  Might work if you already run buster.  If you still run stretch you're out of luck, as the Pi 4 only supports buster.  You should be able to copy over the database and move the ConBee.

**Comment by ChrisPrefect** [comment]
The latest image is from last year?

deCONZ  2.05.72
Version  12-2019
veröffentlicht  17.12.2019

https://phoscon.de/de/conbee/sdcard

Or can I just do these steps on my current Raspian image? Will this update deCONZ?

![image](https://user-images.githubusercontent.com/3579863/84711742-49086280-af67-11ea-9f90-9fcee69642df.png)

 Should I use the beta version?

Thanks a lot!

**Comment by ebaauw** [comment]
I'm sorry, I have no experience with the image, but you should be able to use `apt` to update deconz using these steps.  It takes a bit longer for versions to be pushed to the `stable` channel, so I use the `beta`.  I think you need as least .75.  .78 will be published on beta shortly.

**Comment by ChrisPrefect** [comment]
I managed to upgrade, thanks for your tips! I am now on version .78

The .ota files where copied into the same directory but with different file names. 

But the files are not automatically selected when I click on a node in the graphical overview or in the list. How do I select the right firmware for all the nodes?

![image](https://user-images.githubusercontent.com/3579863/84722498-b32f0080-af83-11ea-9171-8fd76d4a9620.png)


Thank you!

**Comment by ChrisPrefect** [comment]
Update: It worked! After waiting some time, I can now select a row and click on "Query" and it sometimes loads an update. The version number does not change though.

![image](https://user-images.githubusercontent.com/3579863/84723910-153d3500-af87-11ea-9f8a-0bf4128185dc.png)

**Comment by ebaauw** [comment]
> The version number does not change though.

It will on the next _Query_, when the “done” status changes back to “no file”.

> But most of the nodes don't report back their vendor, image or version and do not start an update after a press on Query. Is this normal?

The plugin only updates one device at a time.  The light drives the update process, not the plugin.  The buttons “invite” the light to start the process.  When the light wants to start upgrading and the plugin is busy upgrading another device, it’s up to the light to try again after some time.  Some devices do this every 5 minutes, others take several hours.  If you keep the plugin running for a day, you should see all rows populated (except for unreachable devices).
