### ISSUE TITLE
Highlight device which is clicked in OTA list towards Mesh?

### ISSUE THREAD

**Issue by gvdhoven** [dresden-elektronik/deconz-ota-plugin#14]
Currently clicking on the device in the mesh network selects the right entry in the OTA tab, but selecting a device in the OTA tab doesn't do the same on the mesh network. Don't know if that is feasible at all but it's just an observation.

**Comment by ebaauw** [comment]
I don't think the C++ API, that plugins use to communicate with the deCONZ core provides a call to select a node in the map.  Also, the map doesn't really give a clue as to which node is selected, or does it?  I wanted to implement similar function for the _Node List_ panel, but that's all deCONZ core, closed source, so I cannot change that.

**Comment by ebaauw** [comment]
There's actually two Wiki pages with firmware.  One seems terribly outdated...

**Comment by Webunity** [comment]
I don't know; but clicking a node in the map does update the panel, so i simply thought the other way around was also possible, but i do understand why the current implementation is there (probably a onNodeSelected callback or something). Would it be possible to display the name then in the grid of the OTA panel? This makes identifying entries in the OTA tab a lot easier.

**Comment by ebaauw** [comment]
> probably a onNodeSelected callback or something

Close enough: `deCONZ::NodeEvent::NodeSelected`.

> Would it be possible to display the name then in the grid of the OTA panel? This makes identifying entries in the OTA tab a lot easier.

I don't think so.  The name lives in the REST API plugin, inaccessible to the OTAU plugin.  The REST API plugin uses a `Q_SIGNAL` to update the fields in the table in the _Node list_ panel, but there doesn't seem to be a way for a plugin to read back those values.
