### ISSUE TITLE
IKEA Trådfri CWS bulb, firmware updated but old firmware is still listed as current in deCONZ?

### ISSUE THREAD

**Issue by mwhrtin** [dresden-elektronik/deconz-ota-plugin#15]
Running deCONZ 2.05.59 and a ConBee stick with firmware 26300500, normally `deconz` is started in headless mode on a Raspberry Pi.

**Issue:**
I suspect all my IKEA Trådfri bulb E27 CWS opal 600lm have been updated to the latest firmware version `1.3.009` that was released about a week ago, the bulbs appear to have new functionality/behavior that they didn't have before. But deCONZ still list them as using the older `1.3.002` version. I've tried to reboot, triggering a manual OTAU doesn't do anything, the progress just changes to `Idle`.

Is it possible that the bulb firmware is updated but that deCONZ (for whatever reason) is still listing the older firmware as the bulbs current version?

**Node list screenshot:**
![node_list](https://user-images.githubusercontent.com/2332320/54074680-bffb7980-4295-11e9-91ad-685d8a770332.png)

**OTAU plugin screenshot:**
![otau_plugin](https://user-images.githubusercontent.com/2332320/54074681-c25dd380-4295-11e9-9a34-d291f79c0a4c.png)

**Longer description:**
IKEA released new firmwares about a week ago, I think I remember reading that deCONZ will eventually do an OTAU in the background if there are new firmwares available, so I used `ikea-ota-download.py` to download them.  I verified that the new firmwares were downloaded and a new `117C-2801-13009572.zigbee` file was generated in the `otau` directory. 

Speed forward to today and I noticed that all 5 of my IKEA Trådfri bulb E27 CWS opal 600lm retain both the brightness and the previously used color when power-cycled. This was not the case before, previously they kept the brightness but the color was always reset to 2700K white when cycling the power using an old fashion power switch.

I suspected that perhaps the bulbs had been updated in the background and this was one of the fixes in the new `1.3.009` firmware for the bulb. After a quick search I found other Trådfri CWS owners with the same experience (color is kept) after updating the firmware. So I assumed that this confirmed that my bulbs were now using version `1.3.009`.

But to my surprise when I checked in `deconz-gui` (and in Phoscon), the lights are still listed as using version `1.3.002`. I've tried to reboot in case the firmware version is only read at startup but `1.3.002` is still listed. When I try to perform a manual OTA update using `117C-2801-13009572.zigbee` the progress is immediately changed to `Idle`, no progress is started. I'm not sure if this is because the update fails or if the bulb rejects the update because it's already updated.

**Comment by ebaauw** [comment]
> I confirmed that the old firmware is still listed.

You need to read the _Basic_ cluster attributes in the GUI to refresh these values, see the [README](https://github.com/dresden-elektronik/deconz-ota-plugin).

**Comment by slamp** [comment]
Sorry, i missed that.
For the OSRAM bulb I updated yesterday, the new firmware is displayed in cluster Info after a 'read'. It proved that the firmware went well for the OSRAM bulb but it is still the old version  displayed in the node list (top right). 
For the conBee II itself (screenshot of yesterday, there is no 'read' button in cluster info) 

![osram-fw](https://user-images.githubusercontent.com/714910/84796733-40f90300-aff9-11ea-92b5-04e81eaf92d3.png)

I also have an ikea device `1.3.002`. I will try to update it to `1.3.009` to reproduce (or not) the bug opened by @mwhrtin

**Comment by slamp** [comment]
After restarting deconz docker container the new version is displayed in node list (v1.05.10) for the OSRAM bulb but still not for conbee II

I have an ikea device `1.3.002`. I will try to update it to `1.3.009` to test ifthe bug opened by @mwhrtin is solved

**Comment by ebaauw** [comment]
> The old version of conbee II firmware 0x264a0700 is still listed

The firmware update of the RaspBee or ConBee is something different altogether, not related to the OTAU plugin.

> For the conBee II itself (screenshot of yesterday, there is no 'read' button in cluster info)

Did you configure the _Basic_ cluster in the _Endpoints_ tab of the _deCONZ Network Settings_ window?

**Comment by slamp** [comment]
@ebaauw  thanks for the information. I will check that.

To go back to the original bug, I updated one Ikea device. 
![ikea-1](https://user-images.githubusercontent.com/714910/84897477-ef5a8200-b0a5-11ea-8ebe-ec2cb1309f3d.png)
Then I `read` the attributes in cluster Info. The new version `1.3.009` was displayed. but in the Node List panel, the version was not updated. 
Then I restart Deconz container and this time the new version was displayed in node List panel
![ikea-2](https://user-images.githubusercontent.com/714910/84898347-647a8700-b0a7-11ea-9f2d-d23bf9aaef6d.png)
