### ISSUE TITLE
Get informations about current firmwares from the end-users

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [dresden-elektronik/deconz-ota-plugin#17]
Hey there.

I thought if there will be a chance to share fimrware states across all deconz users.
This could be a optional feature, not forced.

The problem in my point of view is that I do not know what is the latest OTA firmware. Some company did a great job and share ota-list in json format, for example ikea, but others like philips or aqara does not.

**Why not get this data from the user itself?**

Benefits from such a list could be:
-warn the user if the firmware is outdated
-reduce the risk of zigbee security issues
-reduce incompatibility

**Comment by ebaauw** [comment]
deCONZ runs locally and doesn’t provide any means to upload data to a central server (apart from the automatic gateway discovery).  Changing that is beyond the scope of the OTA plugin.

**Comment by sorryusernameisalreadytaken** [comment]
okay. any tips to find the latest fw for each zigbee device?

**Comment by ebaauw** [comment]
- Check the device manufacturer's web site for release notes (for Hue, see: https://www.philips-hue.com/en-us/support/release-notes).  That still doesn't get you the firmware files, but at least you know a newer version is available;
- Check the device manufacturer's download site (see READ_ME);
- Regularly run the `ikea-ota-download.py` script.
