### ISSUE TITLE
Unable to update Hue devices in Australia

### ISSUE THREAD

**Issue by austwhite** [dresden-elektronik/deconz-ota-plugin#23]
I am unable to  update firmware in Australia.
I have several Philips Hue globes, but the firmware files are never found for these devices.
I can open the OTAU module in deConz, but it never gives me an option to update and never shows a firmware file being available.

**Comment by ebaauw** [comment]
You need to download the firmware files manually to `~/otau`, see https://github.com/dresden-elektronik/deconz-ota-plugin#hue-firmware.  On deCONZ restart, the OTAU server should copy them to files with names encoding the _Manufacturer Code_, _Image ID_, and _Version_.

Check the _Vendor_, _Image_ and _Version_ against the filename, to make sure you have the appropriate firmware file.  The plugin won't select files with the same version or older versions.  Some devices support downgrading firmware when you manually select an old file; others (like Hue) don't.
