### ISSUE TITLE
compiling not possible

### ISSUE THREAD

**Issue by Goldsucher** [dresden-elektronik/deconz-ota-plugin#33]
when I try to compile the plugin I get the following error:

----

pi@raspberrypi:~/deconz-ota-plugin $ qmake && make -j2
make -f Makefile.Release
make[1]: Entering directory '/home/pi/deconz-ota-plugin'
g++ -c -pipe -Wno-attributes -Wall -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DDECONZ_DLLSPEC=Q_DECL_IMPORT -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../.. -I../../common -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -Irelease -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o release/std_otau_plugin.o std_otau_plugin.cpp
g++ -c -pipe -Wno-attributes -Wall -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DDECONZ_DLLSPEC=Q_DECL_IMPORT -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../.. -I../../common -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -Irelease -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o release/std_otau_widget.o std_otau_widget.cpp
In file included from std_otau_plugin.cpp:7:0:
std_otau_plugin.h:7:20: fatal error: deconz.h: No such file or directory
 #include "deconz.h"
                    ^
compilation terminated.
Makefile.Release:242: recipe for target 'release/std_otau_plugin.o' failed
make[1]: *** [release/std_otau_plugin.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from std_otau_widget.cpp:7:0:
std_otau_widget.h:5:26: fatal error: deconz/types.h: No such file or directory
 #include "deconz/types.h"
                          ^
compilation terminated.
Makefile.Release:251: recipe for target 'release/std_otau_widget.o' failed
make[1]: *** [release/std_otau_widget.o] Error 1
make[1]: Leaving directory '/home/pi/deconz-ota-plugin'
Makefile:38: recipe for target 'release' failed
make: *** [release] Error 2

----

any idea how I could fix this?

EDIT: I saw that I should install deconz-dev, but it won't found:

----

pi@raspberrypi:~ $ sudo apt install deconz-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package deconz-dev

**Comment by ebaauw** [comment]
What system are you running on?  There use to be an issue with `deconz-dev` on Raspberry Pi OS bullseye, but that’s been fixed with the latest release of deCONZ.

**Comment by Goldsucher** [comment]
I am using raspberry pi os but meanwhile it works after installing the os gui
