### ISSUE TITLE
IKEA KADRILJ window coverage cant control after Button Update

### ISSUE THREAD

**Issue by smartmatic** [dresden-elektronik/deconz-ota-plugin#34]
Hi,

i have update one of my IKEA KADRILJ Button to the latest Firmware. After the update i am not able to control the window coverage anymore.

Here are some results from deCONZ debug log

`
08:57:04:741 Websocket 192.168.178.55:44302 send message: {"e":"changed","id":"47","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2021-12-29T07:57:04.736"},"t":"event","uniqueid":"68:0a:e2:ff:fe:40:29:d7-01-1000"} (ret = 165)
te, mode, lastseen, lastannounced) VALUES ('47', 'Taster_Rollo_Links', 'ZHASwitch', 'TRADFRI open/close remote', 'IKEA of Sweden', '68:0a:e2:ff:fe:40:29:d7-01-1000', '2.3.079', '{"buttonevent":1002,"lastupdated":"2021-12-29T07:57:04.736"}', '{"alert":"none","battery":74,"group":"36","on":true,"reachable":true}', '{"d":515,"ep":1,"in":[0,1,4096],"out":[6,8,258],"p":260}', 'normal', '1', '2021-12-29T07:56Z', '2021-12-29T07:32:32Z')
:"68:0a:e2:ff:fe:40:29:d7-01-1000"},"e":"changed","id":"47","r":"sensors","t":"event","uniqueid":"68:0a:e2:ff:fe:40:29:d7-01-1000"} (ret = 373)
:"68:0a:e2:ff:fe:40:29:d7-01-1000"},"e":"changed","id":"47","r":"sensors","t":"event","uniqueid":"68:0a:e2:ff:fe:40:29:d7-01-1000"} (ret = 373)
08:58:05:816 Websocket 192.168.178.55:44302 send message: {"e":"changed","id":"47","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2021-12-29T07:58:05.809"},"t":"event","uniqueid":"68:0a:e2:ff:fe:40:29:d7-01-1000"} (ret = 165)
te, mode, lastseen, lastannounced) VALUES ('47', 'Taster_Rollo_Links', 'ZHASwitch', 'TRADFRI open/close remote', 'IKEA of Sweden', '68:0a:e2:ff:fe:40:29:d7-01-1000', '2.3.079', '{"buttonevent":1002,"lastupdated":"2021-12-29T07:58:05.809"}', '{"alert":"none","battery":74,"group":"36","on":true,"reachable":true}', '{"d":515,"ep":1,"in":[0,1,4096],"out":[6,8,258],"p":260}', 'normal', '1', '2021-12-29T07:58Z', '2021-12-29T07:32:32Z')

08:54:01:706 [INFO] - Button 1002 - TRADFRI open/close remote, unicast to: 0x0000, endpoint: 0x01, cluster: WINDOW_COVERING (0x0102), action: Open, payload: None, zclSeq: 30
08:54:06:092 reuse dead link (dead link container size now 0)
08:54:07:493 ZCL attribute report 0xCCCCCCFFFE9727F2 for cluster: 0x0001, ep: 0x01, frame control: 0x38, mfcode: 0x0000 
08:54:17:502 [INFO] - Button 1002 - TRADFRI open/close remote, unicast to: 0x0000, endpoint: 0x01, cluster: WINDOW_COVERING (0x0102), action: Open, payload: None, zclSeq: 31
08:54:19:059 Device TTL 4505 s flags: 0x7
08:54:23:500 0x00158D0005292610 error APSDE-DATA.confirm: 0xF0 on task
08:54:25:901 ZCL attribute report 0x00158D00045F91F9 for cluster: 0x0400, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
08:54:25:908 ZCL attribute report 0x00158D00045F91F9 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
08:54:26:528 Set sensor check interval to 100 milliseconds
08:54:34:030 GW firmware version is up to date: 0x26720700
08:54:34:131 [INFO] - Button 1002 - TRADFRI open/close remote, unicast to: 0x0000, endpoint: 0x01, cluster: WINDOW_COVERING (0x0102), action: Open, payload: None, zclSeq: 32
08:54:42:505 remove link for (AF87, 9C59)
08:54:47:883 [INFO] - Button 1002 - TRADFRI open/close remote, unicast to: 0x0000, endpoint: 0x01, cluster: WINDOW_COVERING (0x0102), action: Open, payload: None, zclSeq: 33
08:54:50:338 [INFO] - Button 1003 - TRADFRI open/close remote, unicast to: 0x0000, endpoint: 0x01, cluster: WINDOW_COVERING (0x0102), action: Stop, payload: None, zclSeq: 34
08:54:53:606 0x00158D0005292610 error APSDE-DATA.confirm: 0xF0 on task
`

The firmware of window coverage is: 2.3.073

Is my button bricked?

**Comment by ebaauw** [comment]
No.  And this has nothing to do with the OTA plugin.  With the latest firmware version, many IKEA controllers no longer send group commands.  You either need to bind the controller directly to the blind(s), or use deCONZ rules.

**Comment by smartmatic** [comment]
> No. And this has nothing to do with the OTA plugin. With the latest firmware version, many IKEA controllers no longer send group commands. You either need to bind the controller directly to the blind(s), or use deCONZ rules.

Since i use the blinds i have linked the button to the blind through the Wireless Light Control System.
Is that what you mean with bind the controller directly?

**Comment by ebaauw** [comment]
I don't know what the Wireless Light Control System is, nor what it means by "linking".

"Binding" is the Zigbee term for configuring a device, indicating to where it should send commands from a particular cluster.  See chapter 8 of the deCONZ GUI user manual (under _Help_).

The IKEA controllers used to be bound to a group, and the actuators (or in your case the KADRILJ) would subscribe to that group.  With this setup it's easy to associate ("link"?) actuators to a controller, using the REST API.

However, with the latest firmware, the IKEA controllers no longer send group commands.  The REST API plugin now sets up a unicast binding to the coordinator, so the gateway still issues button events (see your log), but it doesn't setup unicast bindings to actuators, so they no longer receive any commands from the controller.

I your case you want to create a unicast binding from the client (grey) _Window Covering_ cluster of the open/close remote to endpoint 01 of the KADRILJ, with the server (blue) _Window Covering_ cluster.

**Comment by duffbeer2000** [comment]
With Wireless Light Control System he means the old web interface. 
Instead of http://X.X.X.X:8189/pwa usehttp://X.X.X.X:8189/index.html if you go to groups you should be able to do the group binding.

**Comment by smartmatic** [comment]
> I don't know what the Wireless Light Control System is, nor what it means by "linking".
> 

> The IKEA controllers used to be bound to a group, and the actuators (or in your case the KADRILJ) would subscribe to that group. With this setup it's easy to associate ("link"?) actuators to a controller, using the REST API.
> 

> 
> I your case you want to create a unicast binding from the client (grey) _Window Covering_ cluster of the open/close remote to endpoint 01 of the KADRILJ, with the server (blue) _Window Covering_ cluster.
> 

Wireless Light Control System means the old Phoscon Web App!

![Bildschirmfoto 2021-12-29 um 12 33 48](https://user-images.githubusercontent.com/74932663/147659626-229a40e2-7b5a-4b90-a6d2-30dde9a63f41.png)


Thank you for your support! I forgot to check the manual and it shows how easy the binding is!
With the binding the button works again!

Have a nice day!
